webtalk_init -webtalk_dir E:/FPGA/CODE/1_AND_GATE/1_AND_GATE.sim/sim_1/behav/xsim/xsim.dir/AND_GATE_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 18 23:15:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2cd51bed-932d-4bcd-bdee-ecf373dd1963" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb97dd216fa34cd8bdc782c754f86db3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100010 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "17.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1116036451 -regid "" -xml E:/FPGA/CODE/1_AND_GATE/1_AND_GATE.sim/sim_1/behav/xsim/xsim.dir/AND_GATE_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA/CODE/1_AND_GATE/1_AND_GATE.sim/sim_1/behav/xsim/xsim.dir/AND_GATE_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA/CODE/1_AND_GATE/1_AND_GATE.sim/sim_1/behav/xsim/xsim.dir/AND_GATE_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
